---
title: "Busdata Cluster"
runtime: shiny
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}

library(tidyverse)
library(shiny)
library(plotly)
library(DBI)
library(gt)
library(stringr)


banco <- "bd/cluster.db"

conexao <- dbConnect(RSQLite::SQLite(), banco)

cluster_busdata <- bind_rows(
  tbl(conexao, "cluster_busdata_1") %>% collect(),
  tbl(conexao, "cluster_busdata_2") %>% collect(),
  tbl(conexao, "cluster_busdata_3") %>% collect(),
  tbl(conexao, "cluster_busdata_4") %>% collect(),
  tbl(conexao, "cluster_busdata_5") %>% collect(),
  tbl(conexao, "cluster_busdata_6") %>% collect()
)

```

## Agrupamentos dos Dados de Mobilidade

### Informações dos Agrupamentos dos Dados de Mobilidade
```{r}

  cluster_info <- bind_cols(
    list(
      tbl(conexao, "cluster_info_1") %>% collect(),
      tbl(conexao, "cluster_info_2") %>% collect(),
      tbl(conexao, "cluster_info_3") %>% collect(),
      tbl(conexao, "cluster_info_4") %>% collect(),
      tbl(conexao, "cluster_info_5") %>% collect(),
      tbl(conexao, "cluster_info_6") %>% collect()
    ),
    .name_repair = "minimal"
  )
  
  cluster_info <- as.data.frame(t(rowsum(t(cluster_info), group = colnames(cluster_info), na.rm = T)))
  
  cluster_info$dbscan <- c("border", "seed", "total")
  
  cluster_info <- cluster_info %>% 
    select(dbscan, str_sort(colnames(.), numeric = TRUE))
  
output$table_cluster_info <- render_gt({
  
  cluster_info <- cluster_info %>%  
    gt()
  
  cluster_info
  
})

gt_output("table_cluster_info")

downloadLink("download_cluster_info", "Download Informações Cluster")

output$download_cluster_info <- downloadHandler(
  filename = function(){paste("info_cluster", ".csv", sep = "")},
  content = function(file){write.csv(cluster_info, file, row.names = FALSE)}
)

```

### Mapa dos Agrupamentos dos Dados de Mobilidade
```{r}

output$plot_cluster_map <- renderPlotly({
  
  cluster_busdata_sample <- cluster_busdata %>% 
    filter(id_agrupamento != 0) %>% 
    slice_sample(prop = 0.4, replace = FALSE)
  
  fig <- cluster_busdata_sample %>% 
    plot_ly(
      lat = ~lat,
      lon = ~long,
      color = ~id_agrupamento,
      opacity = 0.5,
      type = "scattermapbox",
      mode = "markers",
      marker = list(colorscale = "Rainbow"),
      hoverinfo = "text",
      text = ~paste(
        "Lat:", lat,
        "Long:" , long, "<br>",
        " Agrupamento:", id_agrupamento
      )
    ) %>%
    layout(
      mapbox = list(
        style = "open-street-map",
        zoom = 9.5,
        center = list(lat = -22.9, lon = -43.45)
      )
    ) %>% 
    hide_colorbar() %>% 
    suppressWarnings() # Remove Warnings 
  
  fig
})

plotlyOutput("plot_cluster_map")

downloadLink("download_dados", "Download Dados Cluster")

output$download_dados <- downloadHandler(
  filename = function(){paste("dados_cluster_filtrado", ".csv", sep = "")},
  content = function(file){write.csv(cluster_busdata, file, row.names = FALSE)}
)

```

### Resultados 
```{r}

nome_empresa_garagem <- tribble(
  ~id_agrupamento, ~nome_empresa,
  0,               NA, # ruido
  1,               NA, # N é garagem
  2,               NA, # N é garagem
  3,               "Transriver Transportes", # Vẽ depois 
  4,               "Expresso Pégaso",
  5,               "Expresso Recreio",
  6,               "Auto Viação Jabour",
  7,               "Transportes Campo Grande",
  8,               "Transportes Barra Garagem 2",
  9,               "Viação Pavunense",
  10,              "Viação Novacap S/A",
  11,              "TEL Transportes Estrela",
  12,              NA, # N é garagem
  13,              NA, # N é garagem
  14,              "Transportes Barra",
  15,              "Auto Viação Três Amigos",
  16,              "Viação Redentor/Transportes Futuro", # Vê depois
  17,              "Viação VG",
  18,              "Garagem da Caprichosa/Caprichosa Auto Ônibus",
  19,              "Rodoviária A. Matias",
  20,              "Garagem Gire Transportes - Duque de Caxias",
  21,              "Braso Lisboa",
  22,              "Viação Nossa Senhora de Lourdes",
  23,              "Gire Transportes - Bonsucesso",
  24,              "Transportes Vila Isabel",
  25,              "Real Auto Ônibus",
  26,              NA, # N é garagem
  27,              "Viação Ideal",
)

resultado_agrupamento <- cluster_busdata %>% 
    group_by(id_agrupamento) %>% 
    summarise(
      n = n(),
      lat_max = max(lat),
      lat_min = min(lat),
      long_max = max(long),
      long_min = min(long)
    ) %>% 
    left_join(nome_empresa_garagem) %>% 
    filter(id_agrupamento != 0) %>% 
    gt() %>% 
    cols_label(
      id_agrupamento = "ID Agrupamento",
      n = "Quantidade de Pontos",
      lat_max = "Latitude Max",
      lat_min = "Latitude Min",
      long_max = "Longitude Max",
      long_min = "Longitude Min",
      nome_empresa = "Nome Empresa"
    )

output$table_cluster_resultado <- render_gt({
  
  resultado_agrupamento
  
})

gt_output("table_cluster_resultado")

downloadLink("download_resultado", "Download Resultado")

output$download_resultado <- downloadHandler(
  filename = function(){paste("cluster_resultado", ".csv", sep = "")},
  content = function(file){write.csv(resultado_agrupamento, file, row.names = FALSE)}
)

```

## Agrupamentos Pequenos 

### Informações dos Agrupamentos Pequenos
```{r}

  cluster_info_pequeno <- tbl(conexao, "cluster_info_7") %>% collect()
  
  cluster_info_pequeno$dbscan <- c("border", "seed", "total")
  
  cluster_info_pequeno <- cluster_info_pequeno %>% 
    relocate(dbscan)
  
output$table_cluster_pequeno_info <- render_gt({

  cluster_info_pequeno <- cluster_info_pequeno %>% 
    gt()
  
  cluster_info_pequeno
  
})

gt_output("table_cluster_pequeno_info")

downloadLink("download_cluster_info_pequeno", "Download Informações Cluster Pequeno")

output$download_cluster_info_pequeno <- downloadHandler(
  filename = function(){paste("info_cluster_pequeno", ".csv", sep = "")},
  content = function(file){write.csv(cluster_info_pequeno, file, row.names = FALSE)}
)

```

### Mapa dos Agrupamentos Pequenos
```{r}

output$plot_cluster_pequeno_map <- renderPlotly({
  
  cluster_pequeno <- tbl(conexao, "cluster_busdata_7") %>% 
    collect() %>% 
    filter(id_agrupamento != 0)
  
  fig <- cluster_pequeno %>% 
    plot_ly(
      lat = ~lat,
      lon = ~long,
      color = ~id_agrupamento,
      opacity = 0.5,
      type = "scattermapbox",
      mode = "markers",
      marker = list(colorscale = "Rainbow"),
      hoverinfo = "text",
      text = ~paste(
        "Lat:", lat,
        "Long:" , long, "<br>",
        " Agrupamento:", id_agrupamento
      )
    ) %>%
    layout(
      mapbox = list(
        style = "open-street-map",
        zoom = 9.5,
        center = list(lat = -22.9, lon = -43.45)
      )
    ) %>% 
    hide_colorbar() %>% 
    suppressWarnings() # Remove Warnings 
  
  fig
})

plotlyOutput("plot_cluster_pequeno_map")

downloadLink("download_dados_pequenos", "Download Dados Cluster Pequenos")

output$download_dados_pequenos <- downloadHandler(
  filename = function(){paste("dados_cluster_pequenos", ".csv", sep = "")},
  content = function(file){write.csv(tbl(conexao, "cluster_busdata_7") %>% collect(), file, row.names = FALSE)}
)

```

### Resultados dos Agrupamentos Pequenos
```{r}

resultado_cluster_pequenos <- tbl(conexao, "cluster_busdata_7") %>% 
  collect() %>% 
  group_by(id_agrupamento) %>% 
  summarise(
    n = n(),
    lat_max = max(lat),
    lat_min = min(lat),
    long_max = max(long),
    long_min = min(long)
  ) %>% 
  filter(id_agrupamento != 0) %>% 
  gt() %>% 
  cols_label(
    id_agrupamento = "ID Agrupamento",
    n = "Quantidade de Pontos",
    lat_max = "Latitude Max",
    lat_min = "Latitude Min",
    long_max = "Longitude Max",
    long_min = "Longitude Min",
  )

output$table_cluster_pequeno_resultado <- render_gt({
  
  resultado_cluster_pequenos
  
})

gt_output("table_cluster_pequeno_resultado")

downloadLink("download_cluster_pequeno_resultado", "Download Resultado Cluster Pequenos")

output$download_cluster_pequeno_resultado <- downloadHandler(
  filename = function(){paste("cluster_pequeno_resultado", ".csv", sep = "")},
  content = function(file){write.csv(resultado_cluster_pequenos, file, row.names = FALSE)}
)

```
