---
title: "Relatório Cluster"
output: 
  html_document
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}

library(tidyverse)
library(shiny)
library(plotly)
library(DBI)

banco_destino <- "bd/busdata.db"

conexao <- dbConnect(RSQLite::SQLite(), banco_destino)

cluster_bus <- tbl(conexao, "cluster_bus") %>% 
  collect()


dbDisconnect(conexao)

```


## Dados Utilizados


```{r}

output$plot_dados_bus <- renderPlotly({
  
  fig <- cluster_bus %>%
    plot_ly(
      lat = ~lat,
      lon = ~long,
      marker = list(color = "black"),
      opacity = 0.5,
      type = 'scattermapbox',
      mode = "markers",
      hoverinfo = "text",
      text = ~paste("Lat:", lat, "Long:" , long)
    ) %>% 
    layout(
      mapbox = list(
        style = "open-street-map",
        zoom = 9.5,
        center = list(lat = -22.9125642, lon = -43.45)
      )
    ) %>% 
    suppressWarnings()

  fig
})

plotlyOutput("plot_dados_bus")

```


## Cluster Bus


```{r}

output$plot_cluster_bus <- renderPlotly({
  
  cluster_bus <- cluster_bus %>% 
    filter(id_agrupamento != 0)
  
  fig <- cluster_bus %>% 
    plot_ly(
      lat = ~lat,
      lon = ~long,
      color = ~id_agrupamento,
      opacity = 0.5,
      type = "scattermapbox",
      mode = "markers",
      marker = list(colorscale = "Rainbow"),
      hoverinfo = "text",
      text = ~paste(
        "Lat:", lat,
        "Long:" , long, "<br>",
        " Agrupamento:", id_agrupamento
      )
    ) %>%
    layout(
      mapbox = list(
        style = "open-street-map",
        zoom = 9.5,
        center = list(lat = -22.9, lon = -43.45)
      )
    ) %>% 
    hide_colorbar() %>% 
    suppressWarnings() # Remove Warnings 

  fig
  
})

plotlyOutput("plot_cluster_bus")

```